export default [
    {img : "/sponsor/previoussponsors/polygon.png", link : "https://polygon.technology"},
    {img : "/sponsor/previoussponsors/kotak-logo.png", link : "https://www.kotak.com/en/home.html"},
    {img : "/sponsor/previoussponsors/spectral-logo.png", link : "https://syntax.spectrallabs.xyz/referral?code=mRUDnuhZ"},
    {img : "/sponsor/previoussponsors/Atos.png", link : "https://atos.net/en/india"},
    {img : "/sponsor/previoussponsors/falconx.svg", link : "https://www.falconx.io/"},
    {img : "/sponsor/previoussponsors/unstop.png", link : "https://unstop.com/"},
    {img : "/sponsor/previoussponsors/rirrhys.png", link : "https://rirrhys.com/"},
    {img : "/sponsor/previoussponsors/oishi.jpg", link : "https://www.instagram.com/oishii.sushi6/"},
    {img : "/sponsor/previoussponsors/sybgen.png", link : "https://sybgen.com/"},
    {img : "/sponsor/previoussponsors/Axurewhite.png", link : "https://www.axure.com/"},
    {img : "/sponsor/previoussponsors/mabtheo.webp", link : "https://mabtheo.com/"},
    {img : "/sponsor/previoussponsors/redbull.svg", link : "https://www.redbull.com/in-en/"},
    {img : "/sponsor/previoussponsors/vfsl.webp", link : "https://vfslsnacks.com/"},
    {img : "/sponsor/previoussponsors/beeceptor.svg", link : "https://beeceptor.com/"},
    {img : "/sponsor/previoussponsors/Inspirus_Logo.webp", link : "https://www.inspiruseducation.com/"},
    {img : "/sponsor/previoussponsors/riidllogo1.jpg", link : "https://www.riidl.org/"},
    {img : "/sponsor/previoussponsors/american_tourister.webp", link : "https://www.americantourister.in/"},
    {img : "/sponsor/previoussponsors/learningwhiletraveling.png", link : "https://learningwhiletravelling.com/"},
    {img : "/sponsor/previoussponsors/alan.png",link : "https://alan.app/"},
    {img : "/sponsor/previoussponsors/arcana.svg", link : "https://www.arcana.network/"},
    {img : "/sponsor/previoussponsors/balsamiq.png", link : "https://balsamiq.com/"},
    {img : "/sponsor/previoussponsors/bappa-gold.png"},
    {img : "/sponsor/previoussponsors/belgian-waffles.png", link : "https://thebelgianwaffle.co/"},
    {img : "/sponsor/previoussponsors/BeReal.jpeg", link : "https://bereal.com/en/"},
    {img : "/sponsor/previoussponsors/celo.png", link : "https://celo.org/"},
    {img : "/sponsor/previoussponsors/certopus_light.svg", link : "https://certopus.com/"},
    {img : "/sponsor/previoussponsors/cybrancee.png", link : "https://cybrancee.com/"},
    {img : "/sponsor/previoussponsors/digitalocean.png", link : "https://www.digitalocean.com/"},
    {img : "/sponsor/previoussponsors/echo3D.webp", link : "https://www.echo3d.com/"},
    {img : "/sponsor/previoussponsors/filecoin.png", link : "https://filecoin.io/"},
    {img : "/sponsor/previoussponsors/frappe_new-logo.png", link : "https://frappe.io/"},
    {img : "/sponsor/previoussponsors/fuelerLight.png", link : "https://fueler.io/"},
    {img : "/sponsor/previoussponsors/Gatsby.png", link : "https://gatsbyindia.com/"},
    {img : "/sponsor/previoussponsors/gfg_logo.png", link : "https://www.geeksforgeeks.org/"},
    {img : "/sponsor/previoussponsors/hack-club.png", link : "https://hackclub.com/"},
    {img : "/sponsor/previoussponsors/interviewbuddy.png", link : "https://interviewbuddy.net/"},
    {img : "/sponsor/previoussponsors/interviewCake.png", link : "https://www.interviewcake.com/"},
    {img : "/sponsor/previoussponsors/kaamyuptextlogo.png"},
    {img : "/sponsor/previoussponsors/konfhub.png", link : "https://konfhub.com/"},
    {img : "/sponsor/previoussponsors/newton.png", link : "https://www.newtonschool.co/"},
    {img : "/sponsor/previoussponsors/noticebard.svg", link : "https://noticebard.com/"},
    {img : "/sponsor/previoussponsors/OReilly_logo_white_rgb.png", link : "https://www.oreilly.com/"},
    {img : "/sponsor/previoussponsors/polygon.png", link : "https://polygon.technology/"},
    {img : "/sponsor/previoussponsors/portis.png", link : "https://www.portis.io/"},
    {img : "/sponsor/previoussponsors/Postman.png", link : "https://www.postman.com/"},
    {img : "/sponsor/previoussponsors/Protoio.png", link : "https://proto.io/"},
    {img : "/sponsor/previoussponsors/quicknode.png", link : "https://www.quicknode.com/"},
    {img : "/sponsor/previoussponsors/Replit.png", link : "https://replit.com/"},
    {img : "/sponsor/previoussponsors/riidl.png", link : "https://riidl.org/"},
    {img : "/sponsor/previoussponsors/rorito.jpeg", link : "https://www.instagram.com/roritopensofficial/?igshid=YmMyMTA2M2Y%3D"},
    {img : "/sponsor/previoussponsors/Rosenfeld.jpg", link : "https://rosenfeldmedia.com/"},
    {img : "/sponsor/previoussponsors/sbi.png", link : "https://sbi.co.in/"},
    {img : "/sponsor/previoussponsors/Solana.png", link : "https://solana.com/"},
    {img : "/sponsor/previoussponsors/sticker-mule-logo-white.png", link : "https://www.stickermule.com/"},
    {img : "/sponsor/previoussponsors/Stickertimes.png"},
    {img : "/sponsor/previoussponsors/symbl.png", link : "https://symbl.ai/?utm_source=hackathons&utm_medium=kjsce&utm_campaign=kjsce"},
    {img : "/sponsor/previoussponsors/taskade.jpg", link : "https://www.taskade.com/"},
    {img : "/sponsor/previoussponsors/tezos.png", link : "https://tezos.com/"},
    {img : "/sponsor/previoussponsors/theeducationtree.jpeg", link : "https://theeducationtree.com/"},
    {img : "/sponsor/previoussponsors/TruScholar.png", link : "https://www.truscholar.io/"},
    {img : "/sponsor/previoussponsors/vodex.png", link : "https://vodex.ai/"},
    {img : "/sponsor/previoussponsors/waffleLab.jpeg", link : "https://www.wafflelab.com/"},
    {img : "/sponsor/previoussponsors/wolfram.png", link : "https://www.wolfram.com/"},
    {img : "/sponsor/previoussponsors/zeeve.png", link : "https://www.zeeve.io/"}
]